amcl:
  ros__parameters:
    use_sim_time: false
    enabled: false  # Just a safeguard

map_server:
  ros__parameters:
    use_sim_time: false
    enabled: false

global_costmap:
  global_frame: odom
  robot_base_frame: base_link

local_costmap:
  global_frame: odom
  robot_base_frame: base_link

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_dwb_controller/DWBController"
